### ISSUE TITLE
Run a Core Fullnode - Synchronization does not start

### ISSUE THREAD

**Issue by sippikdf** [coredao-org/core-chain#4]
Hello ,

I tried to run the node but the synchronization does not start. Are there any new boot nodes I can try?

![immagine](https://user-images.githubusercontent.com/113902497/218761759-e0c75d1f-aa26-460b-88e3-08475fdd2b26.png)

Thanks

**Comment by sippikdf** [comment]
Any help ?

**Comment by charles2022wood** [comment]
Have you initialised the genesis block?

**Comment by sippikdf** [comment]
> Have you initialised the genesis block?

Of course I did.

**Comment by charles2022wood** [comment]
Could you print you genesis block hash (when you start a node, you can see it in log), and your config file

**Comment by sippikdf** [comment]
> Could you print you genesis block hash (when you start a node, you can see it in log), and your config file

INFO [02-17|08:21:17.494] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-17|08:21:17.497] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-17|08:21:17.501] Set global gas cap                       cap=50,000,000
INFO [02-17|08:21:17.502] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [02-17|08:21:17.502] Allocated cache and file handles         database=/home/coredao/mainnet/node/geth/chaindata cache=512.00MiB handles=524,288
INFO [02-17|08:21:17.548] Opened ancient database                  database=/home/coredao/mainnet/node/geth/chaindata/ancient/chain readonly=false
INFO [02-17|08:21:17.553]
INFO [02-17|08:21:17.553] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [02-17|08:21:17.553] Chain ID:  1116 (unknown)
INFO [02-17|08:21:17.553] Consensus: unknown
INFO [02-17|08:21:17.553]
INFO [02-17|08:21:17.553] Pre-Merge hard forks:
INFO [02-17|08:21:17.553]  - Homestead:                   0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
INFO [02-17|08:21:17.553]  - Tangerine Whistle (EIP 150): 0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
INFO [02-17|08:21:17.553]  - Spurious Dragon/1 (EIP 155): 0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [02-17|08:21:17.553]  - Spurious Dragon/2 (EIP 158): 0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
INFO [02-17|08:21:17.553]  - Byzantium:                   0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
INFO [02-17|08:21:17.553]  - Constantinople:              0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
INFO [02-17|08:21:17.553]  - Petersburg:                  0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
INFO [02-17|08:21:17.553]  - Istanbul:                    0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
INFO [02-17|08:21:17.553]  - Muir Glacier:                0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
INFO [02-17|08:21:17.553]  - Berlin:                      <nil> (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
INFO [02-17|08:21:17.553]  - London:                      <nil> (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
INFO [02-17|08:21:17.553]
INFO [02-17|08:21:17.553] The Merge is not yet available for this network!
INFO [02-17|08:21:17.553]  - Hard-fork specification: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
INFO [02-17|08:21:17.553] ---------------------------------------------------------------------------------------------------------------------------------------------------------
INFO [02-17|08:21:17.553]
INFO [02-17|08:21:17.554] Disk storage enabled for ethash caches   dir=/home/coredao/mainnet/node/geth/ethash count=3
INFO [02-17|08:21:17.554] Disk storage enabled for ethash DAGs     dir=/root/.ethash                          count=2
INFO [02-17|08:21:17.554] Initialising Ethereum protocol           network=1116 dbversion=8
INFO [02-17|08:21:17.560] Loaded most recent local header          number=0 hash=f7fc87..3357ad td=1 age=1y3mo1w
INFO [02-17|08:21:17.560] Loaded most recent local full block      number=0 hash=f7fc87..3357ad td=1 age=1y3mo1w
INFO [02-17|08:21:17.560] Loaded most recent local fast block      number=0 hash=f7fc87..3357ad td=1 age=1y3mo1w
WARN [02-17|08:21:17.560] Snapshot maintenance disabled (syncing)
INFO [02-17|08:21:17.561] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-17|08:21:17.561] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-17|08:21:17.561] Gasprice oracle is ignoring threshold set threshold=2
WARN [02-17|08:21:17.561] Unclean shutdown detected                booted=2023-02-14T11:32:56+0100 age=2d20h48m
WARN [02-17|08:21:17.561] Unclean shutdown detected                booted=2023-02-14T11:37:50+0100 age=2d20h43m
WARN [02-17|08:21:17.561] Unclean shutdown detected                booted=2023-02-14T11:38:42+0100 age=2d20h42m
WARN [02-17|08:21:17.561] Unclean shutdown detected                booted=2023-02-14T11:41:02+0100 age=2d20h40m
WARN [02-17|08:21:17.561] Engine API enabled                       protocol=eth
WARN [02-17|08:21:17.561] Engine API started but chain not configured for merge yet
INFO [02-17|08:21:17.561] Starting peer-to-peer node               instance=Geth/v1.10.23-stable-8443b60d/linux-amd64/go1.19.3
INFO [02-17|08:21:17.644] New local node record                    seq=1,676,370,874,789 id=167b8e4ff4fb5649 ip=127.0.0.1 udp=40608 tcp=40608
INFO [02-17|08:21:17.644] Started P2P networking                   self=enode://71f8044962bca9bac27643a48c09ca36e7414a8e9a82e9341af02e0b089af9d531ccb76432b8c4c0f590ce2bf3bbf51c7115563f8346af6d3fcbc007eafbb553@127.0.0.1:40608
INFO [02-17|08:21:17.645] IPC endpoint opened                      url=/home/coredao/mainnet/node/geth.ipc
ERROR[02-17|08:21:17.645] Unavailable modules in HTTP API list     unavailable=[satoshi] available="[admin debug web3 eth txpool personal ethash miner net]"
ERROR[02-17|08:21:17.645] Unavailable modules in HTTP API list     unavailable="[db satoshi]" available="[admin debug web3 eth txpool personal ethash miner net engine]"
INFO [02-17|08:21:17.645] Loaded JWT secret file                   path=/home/coredao/mainnet/node/geth/jwtsecret crc32=0xa591c564
INFO [02-17|08:21:17.647] HTTP server started                      endpoint=127.0.0.1:4580 auth=false prefix=/ cors=* vhosts=localhost
INFO [02-17|08:21:17.647] WebSocket enabled                        url=ws://[::]:4581
INFO [02-17|08:21:17.647] WebSocket enabled                        url=ws://127.0.0.1:8588
INFO [02-17|08:21:17.647] HTTP server started                      endpoint=127.0.0.1:8588 auth=true  prefix=  cors=localhost vhosts=localhost
INFO [02-17|08:21:18.486] New local node record                    seq=1,676,370,874,790 id=167b8e4ff4fb5649 ip= udp=40608 tcp=40608
INFO [02-17|08:21:27.709] Looking for peers                        peercount=0 tried=224 static=6
INFO [02-17|08:21:39.213] Looking for peers                        peercount=0 tried=144 static=6
INFO [02-17|08:21:49.257] Looking for peers                        peercount=0 tried=199 static=6
INFO [02-17|08:21:52.692] Block synchronisation started
WARN [02-17|08:21:52.693] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
^CINFO [02-17|08:21:52.875] Got interrupt, shutting down...
WARN [02-17|08:21:52.875] HTTP server graceful shutdown timed out
INFO [02-17|08:21:52.875] HTTP server stopped                      endpoint=127.0.0.1:4580
WARN [02-17|08:21:52.875] HTTP server graceful shutdown timed out
INFO [02-17|08:21:52.875] HTTP server stopped                      endpoint=[::]:4581
WARN [02-17|08:21:52.875] HTTP server graceful shutdown timed out
INFO [02-17|08:21:52.875] HTTP server stopped                      endpoint=127.0.0.1:8588
INFO [02-17|08:21:52.876] IPC endpoint closed                      url=/home/coredao/mainnet/node/geth.ipc
ERROR[02-17|08:21:52.919] Ethereum peer registration failed        id=120785ccb366c083 conn=staticdial err="peerset closed"
INFO [02-17|08:21:52.919] Ethereum protocol stopped
INFO [02-17|08:21:52.919] Transaction pool stopped
ERROR[02-17|08:21:52.919] Failed to journal state snapshot         err="snapshot [0xfcd7f14d941fe379a7a7cec2f65efc89714afa612b420dc8306ec761dc30bc52] missing"
INFO [02-17|08:21:52.919] Writing clean trie cache to disk         path=/home/coredao/mainnet/node/geth/triecache threads=8
INFO [02-17|08:21:52.920] Persisted the clean trie cache           path=/home/coredao/mainnet/node/geth/triecache elapsed="846.74µs"



This ?

**Comment by sippikdf** [comment]
> Could you print your genesis block hash (when you start a node, you can see it in log), and your config file

I don't use config.toml i run the following command : 

geth --datadir /home/coredao/mainnet/node --port 40608 --ws --ws.port 4581 --authrpc.port 8588   --http --http.port 4580 --http.rpcprefix=/ --http.corsdomain=* --http.api 'personal,eth,net,web3,personal,admin,miner,txpool,satoshi,debug' --networkid 1116 --ws.api 'personal,db,eth,net,web3,personal,admin,miner,txpool,satoshi,debug' --ws.origins=* --ws.addr 0.0.0.0 --bootnodes enode://6334cdde2728b17486e4930c29e85128694faf118c23f559c7502e1cb42dd90a54f785c80c6a493d7d6f5ed23f3c9cf75e0392b024e45f7eadc81a84544a45ff@seed4.coredao.org:0?discport=35022,enode://20b605d5ee978c22bfb9ed208a40f2876d3dfafb1c60a6427c4db28e516520ee610cbc2a1c0ee05dd08578a041dc9070d92cf888422ed0869d0666b5103292b4@seed2.coredao.org:0?discport=35022,enode://04ffc724b82e2c52df47e2439a30ca4c0f7aca5ce270f6c6bcdf539581ce2ae4965afd5c5fe19106cd528ed6f379c68687a41310054ee751a73880b2c73e85d8@seed3.coredao.org:0?discport=35022,enode://e9a218f70debcb6a423d68f287c972c717606a70bfed278c2f7a876493d37bc535b05127abddeeca21941fc61497a6ca13387466c75a070050862ca6da11b0ca@seed1.coredao.org:0?discport=35022

And I set up the static nodes in a file in the geth directory: 

[
    "enode://aa997f07ea67aa83ce4269d8d867a1b592eb020ad3983e137f371df078ececdfe8b5e9df4e6e7ac7c95edc5be4314016ccd5ed465abf49ee8d269e03c0302fa8@18.140.54.158:35021",
    "enode://a4efd3a2fc9ae5ac7758e854dee26f8052f7d169690df422a1b0a784821dd9c742fd877f5fc44cdb2415dad5b22e8186fff30ffcbf193f178e8c408d1c12661b@18.140.62.198:35021",
    "enode://2f7cccd01ef5059a100191bd881e1445aa81faf96205a784efb394aab9c5d01d28a12672e1dc808543dc2de5cc455850394a69d1c92b3af33a7d790e923f3793@35.180.135.55:35021",
    "enode://2eebc393d901b127f457a9b8fae5fbe3f3f13172a75dd7f4556a8c16f180033c45eb2470fdd71864a92d0f2ecef8b4b317dff0e15fdf884a18a8affa521ea048@35.180.86.1:35021",
    "enode://e3d64ed01b4ffaabdc0994ee661eddf77f3652305deb37592697285fbcc64ddbfd9a9dbc099db54fbaf94a41515a9b08107b1a17427b04a8345c58fc4b58cfcf@3.17.128.116:35021",
    "enode://31a928a8e2347b8215f1a1d7ec6f5ffe1d2546c239b47f52eb165dca3ce038db73dedf61a577f8333f490f348e25b27d102dba3ec9ea9093973036388b35d027@13.58.157.133:35021"
]

**Comment by sippikdf** [comment]
I have also tried config.toml but the result is the same and some functions are deprecated and I have to remove them. I have also tried old versions of geth. But I encounter the same problem.

**Comment by bolaidedd** [comment]
I have the same problem. Please, how to solve it?

**Comment by charles2022wood** [comment]
```
t=2023-01-17T09:15:19+0000 lvl=info msg="Initialising Ethereum protocol"   network=1116 dbversion=<nil>
t=2023-01-17T09:15:19+0000 lvl=info msg="Loaded most recent local header"  number=0 hash=**0xf7fc87f11e61508a5828cd1508060ed1714c8d32a92744ae10acb43c953357ad** td=1 age=1y2mo1w
```
Can you find the hash 0xf7fc87f11e61508a5828cd1508060ed1714c8d32a92744ae10acb43c953357ad in your log?

**Comment by sippikdf** [comment]
> ```
> t=2023-01-17T09:15:19+0000 lvl=info msg="Initialising Ethereum protocol"   network=1116 dbversion=<nil>
> t=2023-01-17T09:15:19+0000 lvl=info msg="Loaded most recent local header"  number=0 hash=**0xf7fc87f11e61508a5828cd1508060ed1714c8d32a92744ae10acb43c953357ad** td=1 age=1y2mo1w
> ```
> 
> Can you find the hash 0xf7fc87f11e61508a5828cd1508060ed1714c8d32a92744ae10acb43c953357ad in your log?



INFO [02-18|09:29:27.416] Loaded most recent local header          number=0 hash=f7fc87..3357ad td=1 age=1y3mo1w
INFO [02-18|09:29:27.416] Loaded most recent local full block      number=0 hash=f7fc87..3357ad td=1 age=1y3mo1w
INFO [02-18|09:29:27.416] Loaded most recent local fast block      number=0 hash=f7fc87..3357ad td=1 age=1y3mo1w

**Comment by charles2022wood** [comment]
Maybe, Check your p2p port 40608   is public to others

**Comment by charles2022wood** [comment]
1. Check your p2p port 40608 is public to others
2. Check the static nodes file in correct directory.

**Comment by sippikdf** [comment]
> 1. Check your p2p port 40608 is public to others
> 
>     2. Check the static nodes file in correct directory.

Everything is correct. I also tried on another server using the standard ports but encountered the same problem. The static nodes are in the right directory, in fact they are detected at start-up. 
![immagine](https://user-images.githubusercontent.com/113902497/219875186-479434f4-2d29-4651-bd28-4025b454fa02.png)

If you look on discord some users have reported the same problem.

**Comment by charles2022wood** [comment]
If you still failed, I suggest that you follow the official guild step by step. 
All static nodes can be connected. I run a node just now, and the node connects the p2p network immediately.

**Comment by sippikdf** [comment]
> If you still failed, I suggest that you follow the official guild step by step. All static nodes can be connected. I run a node just now, and the node connects the p2p network immediately.

using config.toml ? could I have your config ? So I can do a test.

**Comment by charles2022wood** [comment]
https://docs.coredao.org/developer/node-and-validator/how-to-run-a-core-fullnode

**Comment by sippikdf** [comment]
> https://docs.coredao.org/developer/node-and-validator/how-to-run-a-core-fullnode

I mean the config.toml , did you use the default parameters and it started ?
