### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by babosi911** [coredao-org/core-chain#5]
Hello, do you have a video tutorial on the front-end and deployment of remix ide? I want to make one but I don’t have a factory contract and a deployment contract. I don’t know much about the front-end and back-end. Can you make a tutorial? im qq7522@outlook.com

**Comment by charles2022wood** [comment]
You'd better to learn more about remix ide.

**Comment by denalimarsh** [comment]
@babosi911 check out the following:
- [Remix docs](https://remix-ide.readthedocs.io/en/latest/) - source of truth for all things Remix
- [This tutorial](https://www.geeksforgeeks.org/steps-to-execute-solidity-smart-contract-using-remix-ide/) on deploying a smart contract via Remix is pretty good as well
