### ISSUE TITLE
When will regular community members be able to hash delegate BTC?

### ISSUE THREAD

**Issue by Lmakercoredoge** [coredao-org/core-chain#9]
General community members are waiting for the BTC hash delegation mode, and I wonder when it will be open. Anyone can hash delegate, but there is no notice even after time passes. please answer about my question

**Comment by charles2022wood** [comment]
Generally, hash power is owned by miners / miner pool. If any one has enough hash power to delegate，plz refer to https://docs.coredao.org/developer/delegate-guides/how-to-delegate-hash

**Comment by Lmakercoredoge** [comment]
I just need to output OP_RETRUN, but I don't know how to do this. I would
appreciate it if you could tell me this part

2023년 4월 12일 (수) 오후 6:23, CharlesWood ***@***.***>님이 작성:
